#include "common.h"
#include "stm32h7xx_hal.h"

#ifndef SERIAL_PASSTHROUGH_H
#define SERIAL_PASSTHROUGH_H

typedef enum{
    PASSTHROUGH_OKAY,
    PASSTHROUGH_FAIL
}PASSTHROUGH_RETURN_TYPE;

PASSTHROUGH_RETURN_TYPE PASSTHROUGH_START(UART_HandleTypeDef* huart, DMA_HandleTypeDef* hdma_rx);

PASSTHROUGH_RETURN_TYPE PASSTHROUGH_UART2_CALLBACK();

#endif