#include "common.h"
#include "spi.h"
#include "scheduler.h"

#ifndef LSM6DSO_H
#define LSM6DSO_H

typedef enum{
    IMU_OKAY,
    IMU_WRONG_ID,
    IMU_SETUP_FAILED,
    IMU_FAIL
} IMU_RETURN_TYPE;

IMU_RETURN_TYPE IMU_INIT();
uint32_t IMU_CONVERT_DATA(const task_info_t *task);

void IMU_DATA_READY_INTERRUPT_HANDLER(void);
void IMU_DMA_FINISHED_INTERRUPT_HANDLER(void);

#define LSM6DSO_CONFIG_WRITE 0x7F
#define LSM6DSO_CONFIG_READ 0x80

#define LSM6DSO_INT1_CTRL_ADDRESS 0x0D
#define LSM6DSO_INT1_CTRL_DRDY_G 0x02

#define LSM6DSO_CTRL1_XL_ADDRESS 0x10
#define LSM6DSO_CTRL1_XL_ODR_1666 (0x08 << 4)   // CORRECTLY SET CTLR6_C
#define LSM6DSO_CTRL1_XL_FS_16 (0x01 << 2)      // CORRECTLY SET CTLR8_XL
#define LSM6DSO_CTRL1_XL_MASK_AND 0xFE

#define LSM6DSO_CTRL2_G_ADDRESS 0x11
#define LSM6DSO_CTRL2_G_ODR_1666 (0x08 << 4)    // CORRECTLY SET CTRL7_G
#define LSM6DSO_CTRL2_G_FS_2500 (0x03 << 2)
#define LSM6DSO_CTRL2_G_MASK_AND 0xFE

#define LSM6DSO_CRTL3_C_ADDRESS 0x12
#define LSM6DSO_CTRL3_C_RESET (0x01)  // resets IMU

#define LSM6DSO_CRTL4_C_ADDRESS 0x13
#define LSM6DSO_CTRL4_C_DRDY_MASK (0x01 << 3)   // only set DRDY once filters have setteled
#define LSM6DSO_CTRL4_C_MASK_AND 0b01101110

#define LSM6DSO_CTRL9_XL_ADDRESS 0x19
#define LSM6DSO_CTRL9_XL_I3C_DISABLE (0x01 << 1)

#endif